### PR TITLE
Duration graph now reacts on maxBuilds input.

### PR DESCRIPTION
**Pull request by izzekil**
And on the Test Case Result page there is now a maxBuilds input too.
Duration graph dataset limitation is covered with the similar three unit tests.

### CODE REVIEW

**Comment by jussimalinen** [comment]
Excellent, thanks!

**Comment by jussimalinen** [comment]
I have to plan a new release soon.

**Comment by izzekil** [comment]
Hoorray! I will try to imagine-implement a feature to submit during this weekend.
Maybe graphs with clickable build numbers? (Though not sure how they work yet)

**Comment by izzekil** [comment]
I was too ambitious in my intentions :)
So please proceed with the release.

**Pull request merged**
