### PR TITLE
[JENKINS-29353] MaxBuildsToShow graph parameter has been introduced.

### PR DESCRIPTION
**Pull request by izzekil**
Adressing https://issues.jenkins-ci.org/browse/JENKINS-29353 I've added a maxBuildsToShow parameter as a graph settings. The way it's stored, displayed, and processed is the same as other, i.e. zoomToChanges.

Regards,
Nick

### CODE REVIEW

**Comment by izzekil** [comment]
I promised to add some more tests into the PR. It's still to go, I just haven't free cycles yet.

**Comment by jussimalinen** [comment]
Thanks! I made a couple of changes and pushed them to master, could you take a look at how they seem to you?

I changed the layout a bit so that all labels fit under the width of the graph. To do that I had to shorten "Max builds to show" into "Max builds". I also changed it so that empty value is used instead of value 0 with placeholder value "all". (I thought it might be easier to understand than value 0.)

**Comment by izzekil** [comment]
Awesome! This is my first commit into OSS project :)
I've just pulled your changes and have taken a look. All seems to be fine. Placeholder definitely suites better.
I've closed the corresponding JIRA ticket.

What if I expand this change onto the duration graph too? Not sure how, maybe just use the same value  as for Results graph getting it from cookies.

**Comment by jussimalinen** [comment]
Adding the change to duration graphs also makes a lot of sense. I think it is good idea just to read the same cookie. I would not add another input field just for that. Great if you could add that as well!

Thanks for the contribution and hope this is only the beginning of your open source career :)

**Comment by izzekil** [comment]
Just proposed an implementation for the discussed functionality in PR https://github.com/jenkinsci/robot-plugin/pull/11. Please feel free to review.

**Pull request merged**
