### PR TITLE
Add passed and skipped cases to REST API response

### PR DESCRIPTION
**Pull request by asimell**

### CODE REVIEW

**Review by Tattoo — APPROVED** [review]
LGTM 💖

**Comment by asimell** [comment]
Hi,

Just to be on the absolute safe side, which plugin version, Jenkins version, and RF version are you using? I get the correct output, which does show an empty list when there are no passed or skipped cases.
```
{
...
  "executedSuites" : [
    "A"
  ],
  "failedCases" : [
    "A.T4"
  ],
...
  "passedCases" : [
    "A.T1",
    "A.T2",
    "A.T3"
  ],
  "skippedCases" : [
    
  ],
...
}
```

**Comment by laurenyello** [comment]
@asimell thank you for responding
Jenkins 2.249.1
robotframework==4.1.2

I may not have the permissions to view the plugins - do you know how I could find this plugin's version in the results or console?

**Comment by asimell** [comment]
Currently there is no way to see that from the console output or results page. You need admin access to see the plugin page or ask a person with admin access to check it for you.

Your Jenkins version is lower than is stated in the plugin pom.xml file as the requirement (2.277.4). I'd suggest to update your Jenkins to the current LTS version and see if that fixes the issue. I have Jenkins 2.349 locally and at least that works as expected.

**Pull request merged**
