### PR TITLE
Blue Ocean TestResult Extension

### PR DESCRIPTION
**Pull request by bbara**
Hey,

targeting [JENKINS-40220](https://issues.jenkins-ci.org/browse/JENKINS-40220).
Additionally, some small (and also optional) modernizations (using Java 8, ...) are added.

What do you think about it?

BR,
BB

### CODE REVIEW

**Comment by bbara** [comment]
I will try to add some XPath tests on the BlueOcean page too (as soon as I find some time).

**Comment by Tattoo** [comment]
I think it's a good idea. Thanks for contributing! Please highlight eg. me when you feel the PR starts to be feature-ready :)

**Comment by bbara** [comment]
I'm not sure why I am getting [this problem](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Frobot-plugin/detail/PR-26/6/tests):
```
4.251 [id=821] SEVERE c.g.h.WebConsole$DefaultLogger#error: Error initializing Jenkins JavaScript bundle "jenkins-design-language" ReferenceError: Assignment to undefined "warning" in strict mode
```
which results to
```
requires JavaScript to function properly, please enable JavaScript or use a browser which supports it.
```

When I set a breakpoint and visit the given page, it seems like there is no problem at all...
Unfortunately, I cannot find any BlueOcean tests involving HtmlUnit.

However, I found the [BlueOcean Acceptance Tests](https://github.com/jenkinsci/blueocean-plugin/tree/master/acceptance-tests) with some useful helpers, but these are not exposed anywhere.
So maybe I have to ask one of the BlueOcean maintainers what's the best practice to implement such a test...

**Comment by bbara** [comment]
Couldn't get the XPath test running with Jenkins' HtmlUnit.
Got it running with different test libs but I think adding them would be an overkill.
I think it should be sufficient to test against the provided interface of Blue Ocean anyways.

Added two additional commits regarding the usability (not related to the original PR):
First is that the robot result column is suppressed at Folder items.
Second is that the robot project action is shown at Pipeline projects (which do not extend the AbstractJob class).

@Tattoo just tell me if some more actions (except removing the test force commits) are required to get it merged :) If required, I could also move the two unrelated commits to a new PR.

**Comment by nickbroon** [comment]
It would be great to see this BlueOcean support merged.

**Comment by asimell** [comment]
@bbara This looks good. Thanks for the PR!

As a general guideline, I would appreciate separating different functionalities into separate PRs, but I'll let it pass this time. :)

**Comment by DirkRichter** [comment]
found a regression in this PR, which is solved by rollback to Version 2.0.1:

`D:\Jenkins\workspace\DMM-CID_dev>exit 0 
Robot results publisher started...
-Parsing output xml:
Failed!
java.io.IOException: Parsing of output xml failed!
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:104)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:54)
	at hudson.FilePath.act(FilePath.java:1075)
	at hudson.FilePath.act(FilePath.java:1058)
	at hudson.plugins.robot.RobotParser.parse(RobotParser.java:49)
	at hudson.plugins.robot.RobotPublisher.parse(RobotPublisher.java:221)
	at hudson.plugins.robot.RobotPublisher.perform(RobotPublisher.java:243)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1878)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:427)
Caused by: javax.xml.stream.XMLStreamException: Illegal xml input. Could not find end of element status. Unexpected end of element kw (at line: 36 column: 1)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.xmlException(RobotParser.java:179)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.ignoreUntilEnds(RobotParser.java:251)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.processTest(RobotParser.java:313)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:155)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:153)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:153)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.parseResult(RobotParser.java:123)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:99)
	... 16 more
Build step 'Publish Robot Framework test results' changed build result to FAILURE`

**Comment by bbara** [comment]
Hey @DirkRichter,
could you maybe provide me an example output.xml or some relevant lines around the given problematic line 36?
I will take a look into that.

**Comment by DirkRichter** [comment]
here a sample line 35 and line 36 from output.xml:
```
<status status="PASS" starttime="20200225 14:33:12.060" endtime="20200225 14:33:12.060"></status>
</kw>
```

the status element is correctly closed in line 35. it looks like the new robot plugin do no longer understand the closing </status> tag?

here the head of output.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Rebot 3.1.2 (Python 3.7.3 on win32)" generated="20200225 14:33:25.457" rpa="false">
<suite id="s1" name="Tests" source="D:\CID.Artemis\Files\NTA\Robot\Tests">
<suite id="s1-s1" name="CID" source="D:\CID.Artemis\Files\NTA\Robot\Tests\CID">
<suite id="s1-s1-s1" name="SelfTests" source="D:\CID.Artemis\Files\NTA\Robot\Tests\CID\SelfTests.robot">
<test id="s1-s1-s1-t1" name="ChromeDriverVerification">
<kw name="SetDocumentation" library="Settings" type="setup">
<msg timestamp="20200225 14:33:12.060" level="TRACE">Arguments: [  ]</msg>
<kw name="Set Variable" library="BuiltIn">
<doc>Returns the given values which can then be assigned to a variables.</doc>
<arguments>
<arg>env:${ENV} - browser:${BROWSER} - publicationCheckMode:${PublicationCheckMode}</arg>
</arguments>
<assign>
<var>${docu}</var>
</assign>
<msg timestamp="20200225 14:33:12.060" level="TRACE">Arguments: [ 'env:dev - browser:chrome - publicationCheckMode:all_entities_in_VoD.Publication+Dummy' ]</msg>
<msg timestamp="20200225 14:33:12.060" level="TRACE">Return: 'env:dev - browser:chrome - publicationCheckMode:all_entities_in_VoD.Publication+Dummy'</msg>
<msg timestamp="20200225 14:33:12.060" level="INFO">${docu} = env:dev - browser:chrome - publicationCheckMode:all_entities_in_VoD.Publication+Dummy</msg>
<status status="PASS" starttime="20200225 14:33:12.060" endtime="20200225 14:33:12.060"></status>
</kw>
<kw name="Set Variable If" library="BuiltIn">
<doc>Sets variable based on the given condition.</doc>
<arguments>
<arg>'${SELENIUM_GRID_URL}'!=''</arg>
<arg>${docu} - grid:${SELENIUM_GRID_URL}</arg>
<arg>${docu}</arg>
</arguments>
<assign>
<var>${docu}</var>
</assign>
<msg timestamp="20200225 14:33:12.060" level="TRACE">Arguments: [ "''!=''" | '${docu} - grid:${SELENIUM_GRID_URL}' | '${docu}' ]</msg>
<msg timestamp="20200225 14:33:12.060" level="TRACE">Return: 'env:dev - browser:chrome - publicationCheckMode:all_entities_in_VoD.Publication+Dummy'</msg>
<msg timestamp="20200225 14:33:12.060" level="INFO">${docu} = env:dev - browser:chrome - publicationCheckMode:all_entities_in_VoD.Publication+Dummy</msg>
<status status="PASS" starttime="20200225 14:33:12.060" endtime="20200225 14:33:12.060"></status>
</kw>
```

**Comment by asimell** [comment]
@DirkRichter Which Robot Framework version are you using? Could you also consider creating a [new issue](https://issues.jenkins-ci.org/) for this?

**Comment by DirkRichter** [comment]
robotframework==3.1.2

**Comment by DirkRichter** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-61220

**Comment by asimell** [comment]
Thank you. Let us continue discussion there, instead of a closed PR :)

**Pull request merged**
