### PR TITLE
Support Jenkins Workflow

### PR DESCRIPTION
**Pull request by magnayn**
Simple changes in order to be able to report the robot test status within workflow jobs.

### CODE REVIEW

**Comment by MattFriedmanAfilias** [comment]
I'm trying to determine if I can easily use the robot-plugin within workflow. Can it be done? I can't find any examples.

**Comment by magnayn** [comment]
You can (with the above patch, we're using in production for a week).

Then, add something like the following to your Jenkinsfile (or use the snippet generator)

```java
 step([$class: 'RobotPublisher',
        disableArchiveOutput: false,
        logFileName: 'log.html',
        onlyCritical: true,
        otherFiles: '',
        outputFileName: 'output.xml',
        outputPath: '.',
        passThreshold: 90,
        reportFileName: 'report.html',
        unstableThreshold: 100]);
```

Test results then appear and in the build histories.

**Comment by jussimalinen** [comment]
Thanks for the pull request! It will unfortunately take a while for me to go through this, as I have to familiarise myself with the workflow first..

There also was a reason for compiling the plugin against such an old version of Jenkins (used by a project at a client), but I have to check if that is still relevant. I would expect no.

**Comment by magnayn** [comment]
I had to refactor some tests for later Jenkins which is probably it (the HTML format has changed).

Workflow is pretty easy, it's just a minor API change and support SimpleBuildStep.

**Comment by tisto** [comment]
+1 It would be great if this pull request could be merged.

**Comment by magnayn** [comment]
You can (with this patch).

step([$class: 'RobotPublisher',
  disableArchiveOutput: false,
  logFileName: 'log.html',
  onlyCritical: true,
  otherFiles: '',
  outputFileName: 'output.xml',
  outputPath: '.',
  passThreshold: 90,
  reportFileName: 'report.html',
  unstableThreshold: 100]);

**Comment by jussimalinen** [comment]
I hope I will have time to look at this next week. This week I am rather busy on doing some workshops.

**Comment by jussimalinen** [comment]
Looks good. I can merge this as soon as I first fix some performance issues related to other pr that has already been merged. (#13).

**Comment by izzekil** [comment]
Hi @jussimalinen, it would be really helpful to have this PR merged, is there any chance of this in near future?

**Comment by izzekil** [comment]
@magnayn do you use your version (with Workflow support) build in production? I am considering switching to your branch until it's merged.

**Comment by magnayn** [comment]
yup, we do (we're workflow only these days).

The change isn't that big, really. I even refactored the tests to work.

**Comment by izzekil** [comment]
@magnayn am I correct that with using of Jenkins Pipeline the trend graph on the job page are not shown? lastCompletedBuild permalink might serve as a replacement but not in all cases.

**Comment by magnayn** [comment]
Yes. You could probably modify the code to make it add to the workflow job
itself - I suspect it's attaching to the build "step" so not being shown.

**Comment by tisto** [comment]
Any news on this? I would really love to see this getting merged.

**Comment by selurvedu** [comment]
+1

**Comment by Leits** [comment]
+1

**Comment by tisto** [comment]
@magnayn @jussimalinen is there anything I could do to help to make this happen?

**Comment by jussimalinen** [comment]
Right, sorry about that. I changed clients and I have been really busy. I will try to merge this soon.

**Comment by jussimalinen** [comment]
If someone wants to make this happen as soon as possible, they can help by creating a pull request setting the change in #13 by default disabled and then creating another pullrequest the conflicts in this are resolved.

**Comment by jussimalinen** [comment]
There we go, fricking finally... I'll make a release on Friday. So if anyone has anything else to contribute before that, I can squeeze that in.

**Comment by tisto** [comment]
@jussimalinen Awesome! Thank you so much! Can't wait to give it a try!

**Comment by ssinghalu** [comment]
When I am running my automation task in parallel in pipeline, the final report I am getting is the task finished last, how can we handle this.

**Comment by byteknacker** [comment]
Do I need to archive the test results first and then use the RobotPublisher class to retrieve and display the tests? 

My Jenkinsfile:

```
    node(test-node) {
        withEnv([
        "TEST_ENV=something",
        "BUILD_BRANCH=${buildbranch}",
        "JENKINS_TEST_DJANGO_APPS=${apps}",
        "DISPLAY=:${env.EXECUTOR_NUMBER}"]) {
            gitcheckout("${env.BUILD_BRANCH}")
            if ( test == 'robot_tests_mig' ) {
                wrap([$class: 'Xvfb', shutdownWithBuild: true, displayName: env.EXECUTOR_NUMBER.toInteger()]) {
                    sh "tools/jenkins/run.sh ${test}"
                    step([$class: 'ArtifactArchiver', artifacts: '**/robot_logs/mig/*', fingerprint: true])
                    step([$class: 'RobotPublisher', disableArchiveOutput: false, logFileName: 'log.html', onlyCritical: true, otherFiles: '', outputFileName: 'output.xml', outputPath: '.', passThreshold: 90, reportFileName: 'report.html', unstableThreshold: 100]);
                    sh 'kill -9 $(pgrep -f "Xvfb :$EXECUTOR_NUMBER")'
                }
            } else if ( test == 'django_tests' ) {
                sh "tools/jenkins/run.sh ${test}"
                step([$class: 'JUnitResultArchiver', testResults: 'nosetests.xml'])
            }
        }
    }
```

**Comment by byteknacker** [comment]
@magnayn thanks a lot for this PR, it really saved me a lot of time to develop my Jenkinsfile. Would you mind to add some additional descriptive and explanatory comments for the variables for the RobotPublisher class?

**Comment by iwelch82** [comment]
@ssinghalu if you are running jobs in parallel you need to stash the output.xml files from each of the jobs and the unstash them after your `parallel()`. After unstashing you need to run `rebot` to combine all the outputs into a new output. Run `rebot --help` for more details on running rebot. Here is some code I put together to support this combining of results. 

`parallel (
	"stream 1" : {
		node('Pumpkin-Pi') {
			sh "echo lets test this, Hurt me plenty once"
			//TODO: move the checout to the build step and stash the files for use later in the pipeline
			git url: "git@gitlab.com:CEC-TEST/RobotFramework.git", branch: 'develop'
			sh "sudo pybot --include renew_smoke --noncritical non_critical --nostatusrc -o pumpkin-output.xml ."	
			sh "ls -al"
			stash includes: 'pumpkin-output.xml', name: 'pumpkin-results'
			}
	},
	"stream 2" : {
		node ('Blueberry-Pi') {
			sh "echo lets test this, Hurt me plenty twice"
			git url: "git@gitlab.com:CEC-TEST/RobotFramework.git", branch: 'develop'
			sh "sudo pybot --include renew_gpsORcell --noncritical non_critical --nostatusrc -o blueberry-output.xml ."
			sh "ls -al"
			stash includes: 'blueberry-output.xml', name: 'blueberry-results'
			}
	},
	"stream 3" : {
		node {
			sh "sleep 2s"
			sh "echo lets test this, Hurt me plenty three times"
			sh "ls -al"
			}
	}
)
node ('Raspberry-Pi'){
	unstash 'blueberry-results'
	unstash 'pumpkin-results'
	sh "ls -al"
	sh "rebot --noncritical non_critical *.xml"
	step([$class: 'RobotPublisher',
				disableArchiveOutput: false,
				logFileName: 'log.html',
				onlyCritical: true,
				otherFiles: '',
				outputFileName: 'pumpkin-output.xml',
				outputPath: '.',
				passThreshold: 90,
				reportFileName: 'report.html',
				unstableThreshold: 100]);
	}`

**Comment by ssinghalu** [comment]
Thanks @iwelch82 , I also achieved the intended in the same way, but just thinking how if the "rebot" part itself handled by robotframework plugin. As some system might not have robot framework installation & they might using the maven plugin & for that if we want to use "rebot" we need to use robotframework api which is in m2 repo.

**Pull request merged**
